export default {
  topData: [],
  newData: [],
  address: [],
  checkedAddress: null,
  platform: null,
  goods: [],
  payData: {},
  goPayNumber: {},
  totalPrice: 0.00,
  totalNum: 0,
  isTabbar: true,
  detailData: [],
  userData: {},
  consumAmount: null,
  inviteUser: null,
  walletData: {},
  cashData: {},
  orderData: {},
  maintainItem: {},
  provinceArr: [],
  cityArr: [],
  areaArr: []
}
